-- MySQL Script generated by MySQL Workbench
-- Sun Sep 27 12:14:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IStoreDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IStoreDB` ;

-- -----------------------------------------------------
-- Schema IStoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IStoreDB` DEFAULT CHARACTER SET utf8 ;
USE `IStoreDB` ;

-- -----------------------------------------------------
-- Table `IStoreDB`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`categories` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL DEFAULT NULL,
  `title` NVARCHAR(256) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`products` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(256) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `image` MEDIUMBLOB NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `IStoreDB`.`categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`comments` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`comments` (
  `id` INT NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `text` MEDIUMTEXT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `IStoreDB`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`userroles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`userroles` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`userroles` (
  `id` INT NOT NULL,
  `title` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`users` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credentials` NVARCHAR(256) NOT NULL,
  `email` NVARCHAR(128) NOT NULL,
  `passwordhash` NVARCHAR(256) NOT NULL,
  `birthday` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment` NVARCHAR(256) NULL,
  `userrole_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_role1_idx` (`userrole_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`credentials` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_user_userrole`
    FOREIGN KEY (`userrole_id`)
    REFERENCES `IStoreDB`.`userroles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `IStoreDB`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`log` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL,
  `severity` NVARCHAR(50) NOT NULL,
  `logger` TINYTEXT NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`supplier_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`supplier_products` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`supplier_products` (
  `id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `delivery time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier products_supplies1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_supplier products_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_products_suppliers1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `IStoreDB`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `IStoreDB`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
