-- MySQL Script generated by MySQL Workbench
-- Thu Sep 10 00:04:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IStoreDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IStoreDB` ;

-- -----------------------------------------------------
-- Schema IStoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IStoreDB` DEFAULT CHARACTER SET utf8 ;
USE `IStoreDB` ;

-- -----------------------------------------------------
-- Table `IStoreDB`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`categories` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(256) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`products` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `image` VARCHAR(128) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `IStoreDB`.`categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`comments` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`comments` (
  `id` INT NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `text` MEDIUMTEXT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `IStoreDB`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`user_role` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`user_role` (
  `user_role_id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IStoreDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`users` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_user_role1_idx` (`user_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `IStoreDB`.`user_role` (`user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IStoreDB`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IStoreDB`.`orders` ;

CREATE TABLE IF NOT EXISTS `IStoreDB`.`orders` (
  `order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count_of_product` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_order_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `IStoreDB`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `IStoreDB`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
